//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiMovie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cast
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Movie_Id { get; set; }
    
        public virtual Movy Movy { get; set; }
    }
}
